### PR TITLE
Replace YAML safe_load with load(content, safe: true)

### PR DESCRIPTION
**Pull request by hsong-rh**
#17 
#19

### CODE REVIEW

**Comment by hsong-rh** [comment]
@roliveri @jerryk55 Please review.

**Comment by hsong-rh** [comment]
@jerryk55 It's discussed before: we just ignore RuboCop's complaints about hash-rockets syntax.

**Comment by hsong-rh** [comment]
@jerryk55 @roliveri Maybe I should change the :safe to also use the newer format: YAML.load(content, safe: true).

**Comment by hsong-rh** [comment]
@jerryk55 I put the fix for #19 here, no need to open a separate PR for it.

**Comment by jerryk55** [comment]
@hsong-rh that looks good.  Thanks.

**Comment by hsong-rh** [comment]
@roliveri Changed to use 'safe: true' consistently.

**Comment by jerryk55** [comment]
@hsong-rh @roliveri can we get this merged soon?  I keep hitting an issue this PR fixes when I run bundle update on my appliance (and then I hand-edit the gem to insert these changes).

**Pull request merged**
