### PR TITLE
Make repo consistent

### PR DESCRIPTION
**Pull request by juliancheal**
A couple of changes to make this repo consistent with others.

### CODE REVIEW

**Comment by juliancheal** [comment]
It looks like Travis is not enabled for this repository.

**Comment by juliancheal** [comment]
@miq-bot add_label wip

**Comment by Fryguy** [comment]
This repo is not an engine, so shouldn't have things like spec/manageiq in the .gitignore

**Comment by Fryguy** [comment]
The rest looks good to me.

**Comment by juliancheal** [comment]
> This repo is not an engine, so shouldn't have things like spec/manageiq in the .gitignore

All Removed.

**Comment by juliancheal** [comment]
@miq-bot remove_label wip

**Comment by juliancheal** [comment]
Hmm, can't seem to get Codeclimate to retry.

**Comment by juliancheal** [comment]
@Fryguy not sure what's up with Codeclimate. But I think apart from that this PR should be good to go.

**Pull request merged**
