### PR TITLE
Drop Ruby 2.7

### PR DESCRIPTION
**Pull request by Fryguy**
Drop Ruby 2.7

### CODE REVIEW

**Review by jrafanie — APPROVED** [review]

**Comment by Fryguy** [comment]
@agrare Seems master is broken here?  Not sure what to do here.  (Though we could probably merge this one on red)

**Comment by jrafanie** [comment]
Looks like a zeitwerk issue if I'm not mistaken... I thought I fixed that

**Comment by jrafanie** [comment]
> Looks like a zeitwerk issue if I'm not mistaken... I thought I fixed that

might be similar to this... looking at it... https://github.com/ManageIQ/manageiq-smartstate/pull/177

**Comment by jrafanie** [comment]
> > Looks like a zeitwerk issue if I'm not mistaken... I thought I fixed that
> 
> might be similar to this... looking at it... [ManageIQ/manageiq-smartstate#177](https://github.com/ManageIQ/manageiq-smartstate/pull/177)

Opened https://github.com/ManageIQ/amazon_ssa_support/pull/106 to fix this.

**Review by jrafanie — APPROVED** [review]

**Pull request merged**
