### PR TITLE
update aws-sdk gem to v3

### PR DESCRIPTION
**Pull request by AlexanderZagaynov**
This is a part of global update `aws-sdk` gem to `v3`

Together with:
- https://github.com/ManageIQ/manageiq-providers-amazon/pull/488
- https://github.com/ManageIQ/manageiq/pull/19411
- https://github.com/ManageIQ/manageiq-gems-pending/pull/449

It should fix https://github.com/ManageIQ/manageiq-providers-amazon/issues/465

### CODE REVIEW

**Comment by AlexanderZagaynov** [comment]
All tests are green on my machine with patched versions of all gems mentioned here.

**Comment by agrare** [comment]
@roliveri @hsong-rh can you review?

**Comment by roliveri** [comment]
@AlexanderZagaynov Do we know the cause of the Travis failure?

**Comment by agrare** [comment]
@roliveri I assume it is because not all of the dependent PRs have been merged (e.g. gems-pending still requires < 3.0)

**Comment by roliveri** [comment]
I'm sure it's correct, but could you explain: we're updating the aws-sdk gem to v3, yet we're adding dependancies to its constituent gems ~> 1.0. Is that correct?

Plus, do the related PRs need to be merged in any specific order?

**Comment by AlexanderZagaynov** [comment]
@roliveri @agrare yes, all PRs should me merged at once. I've tested them all locally and fixed issues found, so I believe travis will be green after merge. About v1 - yes, it's right, you can check all dependent gems versions here:
https://rubygems.org/gems/aws-sdk/versions/3.0.1 `->` https://rubygems.org/gems/aws-sdk-resources `->` ...

**Comment by agrare** [comment]
@roliveri once you approve this I can merge the other PRs but I'm not a merger here so I'll need you to merge it

**Comment by roliveri** [comment]
@agrare Let me know when you want me to merge this.

**Comment by agrare** [comment]
@roliveri merge away, core PRs have been merged

**Comment by agrare** [comment]
@roliveri `upstream/hammer` for manageiq core is failing because it pulls in amazon_ssa_support master.
Can we either version and release this properly or add release branches (hammer/ivanchuk/master) ?

**Comment by agrare** [comment]
cc @simaishi ^

**Comment by roliveri** [comment]
Should we just create a hammer branch before this merge? I've been out of git for a while, not sure how to do that.

**Comment by simaishi** [comment]
> Can we either version and release this properly or add release branches (hammer/ivanchuk/master) ?

Or maybe we can just tag? This blocks today's downstream build...

cc @Fryguy

**Comment by himdel** [comment]
Looks like this PR breaks gaprindashvili:
:point_up: [October 22, 2019 12:03 PM](https://gitter.im/ManageIQ/manageiq?at=5daef018e886fb5aa2d55a0c)

**Pull request merged**
